const CLOCKWISE_COLORS = ["Red", "Green", "Yellow", "Blue"];
const TOKENS_PER_COLOR = 4;
const COMMON_PATH_LENGTH = 52;
const HOME_LANE_LENGTH = 6;
const FINAL_PROGRESS = COMMON_PATH_LENGTH + HOME_LANE_LENGTH - 1;
const START_PATH_INDEX_BY_COLOR = {
  Red: 13,
  Green: 39,
  Yellow: 26,
  Blue: 0,
};
const SAFE_PATH_INDEXES = new Set([0, 13, 26, 39]);
const ROOM_TTL_MS = 60 * 60 * 1000;
const DISCONNECT_GRACE_MS = 2 * 60 * 1000;

module.exports = {
  CLOCKWISE_COLORS,
  TOKENS_PER_COLOR,
  COMMON_PATH_LENGTH,
  HOME_LANE_LENGTH,
  FINAL_PROGRESS,
  START_PATH_INDEX_BY_COLOR,
  SAFE_PATH_INDEXES,
  ROOM_TTL_MS,
  DISCONNECT_GRACE_MS,
};
